server:
  port: 8080
logging:
  level:
    com:
      crush:
        security:
          mapper: DEBUG
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
spring:
  application:
    name: secutiry
  datasource:
    name: defaultDataSource
    password: 123456
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
token:
  expire: 3600000
  key: 123456
